version: '3.8'
services:
  apigateway:
    build: ./apigateway
    ports:
      - "5000:80"
    depends_on:
      - orderservice
      - productservice

  orderservice:
    build: ./orderservice
    ports:
      - "5100:80"

  productservice:
    build: ./productservice
    ports:
      - "5101:80"

  ordersdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5432:5432"

  productdb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
